declare module "lucide-react" {
  import type { FC, SVGProps } from "react";
  interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number;
    absoluteStrokeWidth?: boolean;
  }
  type LucideIcon = FC<IconProps>;
  export const Play: LucideIcon;
  export const Loader2: LucideIcon;
  export const Phone: LucideIcon;
  export const Stethoscope: LucideIcon;
  export const User: LucideIcon;
  export const LogOut: LucideIcon;
  export const Calendar: LucideIcon;
  export const CalendarIcon: LucideIcon;
  export const Clock: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const CalendarCheck: LucideIcon;
  export const UserCog: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const Leaf: LucideIcon;
  export const Activity: LucideIcon;
  export const UserRound: LucideIcon;
  export const HeartPulse: LucideIcon;
  export const Check: LucideIcon;
  export const Video: LucideIcon;
  export const ShoppingCart: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const MapPin: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const Award: LucideIcon;
  export const BookOpenCheck: LucideIcon;
  export const HeartHandshake: LucideIcon;
  export const Facebook: LucideIcon;
  export const Instagram: LucideIcon;
  export const Youtube: LucideIcon;
  export const Mail: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronDownIcon: LucideIcon;
  export const ChevronLeftIcon: LucideIcon;
  export const ChevronRightIcon: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const Search: LucideIcon;
  export const Circle: LucideIcon;
  export const PanelLeft: LucideIcon;
  export const GripVertical: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const X: LucideIcon;
  export const Minus: LucideIcon;
  export const Menu: LucideIcon;
  export const Star: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const Package: LucideIcon;
  export const Save: LucideIcon;
  export const Users: LucideIcon;
  export const Plus: LucideIcon;
  export const Pencil: LucideIcon;
  export const Trash2: LucideIcon;
  export const Activity: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Copy: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const PhoneOff: LucideIcon;
  export const AlertTriangle: LucideIcon;
}
